export { default as TrendingList } from './Trending/TrendingList';
export { default as CustomNavbar } from './Navbar/CustomNavbar';
export { default as Trending } from './Trending/Trending';
export { default as Footer } from './Footer/Footer';
export { default as Movies } from './Movies/Movies';
export { default as Rate } from './Rate/Rate';
export { default as TVShows } from './TV Shows/Details/TVShows';
export { default as Seasons } from './TV Shows/Seasons/Seasons';
export { default as Episodes } from './TV Shows/Episodes/Episodes';
export { default as Search } from './Search/Search';